### ISSUE TITLE
Refactoring ArcOS & implementing build systems

### ISSUE THREAD

**Issue by keesvv** [IzK-ArcOS/ArcOS-Environment#3]
As the codebase grows, it might be time to rethink the project structure, code and build systems.

Right now, ArcOS doesn't use build systems aside from `electron-packager`, has no project-wide linter, is written in plain JavaScript and CSS without preprocessors, does not follow directory structure conventions and the codebase is – overall – very messy. It's also tightly coupled to the Electron runtime which makes it harder to run it using, say, the Tauri framework.

The following list proposes a refactoring roadmap in chronological order:

- [x] Implement ESLint & Prettier
- [ ] Rethink the project structure
- [ ] Implement ESBuild
- [ ] Use ES Modules
- [ ] Switch from CSS to SCSS
- [ ] Switch from JavaScript to TypeScript
- [ ] Improve classes to follow SOLID principles
- [ ] Decouple ArcOS from Electron
- [ ] Refactor the codebase

This list will be updated from time to time. Feel free to add on to or to correct this list.

**Comment by IzKuipers** [comment]
Closing issue due to the fact that this part of ArcOS has been discontinued in July of 2022.
